### PR TITLE
Simplify ParseContext

### LINKED ISSUE #136: Simplify ParseContext
`contextxs.ParseContext` still carries inneficiencies and complications from its original versions:

* Although the `ast` and `cst` stacks were merged, the `cut` and `pos` stacks remain separate, when there could be a single stack to hold the state at relevant points in the parse: rules, and optionals (used in choices and closures). It should basically be pushing a new state on `_try`,  pop-merge on success, and pop on failure, modifying `tokenizer.pos` on each pop.
* `invoke_rule` should use `with self._try()` instead of pulling its own.
* There should be no need to keep separate `cst` and `ast`, as the `ast` overrides the `cst` in all parser results.
* The `last_node` protocol is suspicious. Why isn't it `current_state.ast`?

The simplifications would allow for semantics and an implementation that can be ported to other programming language targets, such as `C`.

### PR DESCRIPTION
**Pull request by apalala**
closes #136

### CODE REVIEW

**Comment by apalala** [comment]
Could you take a look at these changes, @Victorious3? All tests are passing.

**Review by Victorious3 — CHANGES_REQUESTED** [review]
6eb7953
Why was this removed? It causes an invalid parse in my project where `type word(14.5)` parses as
```
Program [
 Call {
  args = [
   CallArg {
    value = Float 12.4
   }
  ]
  left = Identifier [
   'word'
  ]
 }
]
```
except `word` being a reserved identifier. This is the rule for Identifier:
```
@name
t_ident = /(?!\d)\w+/;

identifier::Identifier::Expression = [root: '::'] ident:'::'.{t_ident}+;
```

**Comment by Victorious3** [comment]
Another thing that happened is that the empty program no longer gives me `None` but instead I get 
```
>       assert parse("") == parse("()") == Program(None)
E       AssertionError: assert 
E         Program [
E          None
E         ]
E         ==
E         Program [
E          [
E           '('
E           ')'
E          ]
E         ]
```
I'll look into this more to figure out what commit causes it, it might actually be a problem with my grammar.

**Comment by apalala** [comment]
@Victorious3 , I tested my Java and COBOL parsers with this version, and had no changes to make to the grammars.

**Comment by Victorious3** [comment]
When I call trace I get this:
```
INFO     tatsu:_common.py:55 ↙t_ident↙identifier↙stmt_typedecl_lhs↙stmt_typedecl↙stmt↙ ~1:6
word(12.4)
INFO     tatsu:_common.py:55 ≡'word' /(?!\d)\w+/
```
Except `word` being a reserved word.
I could add you to my repo to investigate this. Should I do that?

**Comment by Victorious3** [comment]
This fixes my second issue, for the first one I would revert 3288a6a as it breaks `@name`

**Comment by apalala** [comment]
@Victorious3, now `_check_name()` is called automatically from `_invoke_semantic_rule()`. 

I think that the problem may be the

```python
        if not isinstance(name, str):
            return
```

That I added to `_check_name()`. Can you check again?

**Comment by Victorious3** [comment]
Same issue as before. I believe is_name is never set to true? There is no decorator for the generated parser.

**Comment by apalala** [comment]
> Same issue as before. I believe is_name is never set to true? There is no decorator for the generated parser.

Ah! Good catch, @Victorious3 ! 🥇

**Comment by apalala** [comment]
@Victorious3 , I added a unit test for the case you report, and it failed. I added the `@isname` decorator for `@name` rules, and the issue is fixed. I'm merging now.

**Pull request merged**
