### PR TITLE
Issue/62

### PR DESCRIPTION
**Pull request by r-chaves**
Proposed fix for #62 .

### CODE REVIEW

**Comment by apalala** [comment]
Hey @r-chaves! Thanks for the analysis and the pull request!

I'll refactor it a bit before merging so it goes more to the bottom of things.

**Comment by r-chaves** [comment]
:+1: 
I also realized that I didn't add a regression test. Happy to do that if you aren't already taking care of it yourself.

**Comment by apalala** [comment]
Oh, please add the tests! :-)

**Comment by r-chaves** [comment]
Sorry for the delay; I've added a regression test for #62. It probably also needs refactoring to fit better into the testing model, but sadly I am not a tox expert. Hopefully you can do this as part of the pull?

**Comment by apalala** [comment]
fixes #62

**Pull request merged**
