### PR TITLE
renamed tests in test so that unittest can recognize them automatically

### PR DESCRIPTION
**Pull request by bookofproofs**

### CODE REVIEW

**Comment by apalala** [comment]
I'm sorry, @bookofproofs. The official testing tool for the project is `pytest`. Traces of `unittest` are gradually being removed the project.

**Comment by bookofproofs** [comment]
no problem, by the way, pytest also supports "test_" prefixed filenames

**Comment by bookofproofs** [comment]
All tests failed, at least in my fork.

**Comment by apalala** [comment]
`unittest` is deprecated in TatSu.

**Pull request closed without merging**
