### PR TITLE
5.7.4 Release

### PR DESCRIPTION
**Pull request by dnicolodi**
Contains also merge commit submitted in #283

### CODE REVIEW

**Comment by apalala** [comment]
Hey, @dnicolodi! Please merge or rebase to avoid the changes that are not part of your commits?

**Comment by dnicolodi** [comment]
Rebased.

**Comment by apalala** [comment]
I think that the version number change should be included in this pull request.

**Comment by dnicolodi** [comment]
The version number change is already in the `py38_compatibility` branch

**Comment by dnicolodi** [comment]
Thanks @apalala. Let me know if there is anything else I can help with for getting this release out of the door.

**Pull request merged**
