### PR TITLE
Fix NodeWalker methods

### PR DESCRIPTION
**Pull request by by-Exist**
Change the key used to store the walker from id(node.\_\_class__) to node.\_\_class__.\_\_qualname__.

### CODE REVIEW

**Comment by apalala** [comment]
Please also update `CHANGELOG.rst`?

**Comment by by-Exist** [comment]
> Please also update `CHANGELOG.rst` under the `X.Y.Z` release?

Added a new commit. Please review.

**Comment by apalala** [comment]
You did not remove `NodeWalkerMeta`, and it should not be removed!

**Comment by apalala** [comment]
Now there are failing tests in the pipeline.

**Comment by by-Exist** [comment]
This is my first pull request, so I'm inexperienced. sorry.

If I don't remove NodeWalkerMeta, are the other changes accepted?

**Review by apalala — APPROVED** [review]

**Comment by apalala** [comment]
Thanks you!

**Comment by by-Exist** [comment]
> Thanks you!

Looking back, I think the _find_walker method should be a class method. What do you think?

**Comment by apalala** [comment]
Modern linters often point to methods that could be class methods, static methods, or functions.

Personally, I seldom create a class method unless invoking the method without an instance is needed. If some static functionality is reusable, I move it to module aimed for reuse; otherwise, I leave it within the class.

**Pull request merged**
