### PR TITLE
Typehints & Documentation [WIP]

### PR DESCRIPTION
**Pull request by Victorious3**
PR to track Progress. This will break 2.7 support.

I will try to rework the docs as well so that this is used: http://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html to prevent writing documentation twice

- [x] tool.py
- [ ] walkers.py
- [x] rendering.py
- [ ] semantics.py
- [ ] objectmodel.py
- [ ] ast.py
- [ ] grammars.py
- [ ] infos.py

Optional:
- [ ] buffering.py
- [ ] exceptions.py

### CODE REVIEW

**Comment by Victorious3** [comment]
@apalala There are several undocumented Walkers in `walkers.py` where I could only guess what they are meant for.

**Comment by Victorious3** [comment]
I'm sorry for not doing this earlier, sadly I'm on sick leave now and can't work on it for quite some time (probably)

**Comment by apalala** [comment]
Get well, @Victorious3 ! There's no hurry. With your contributions, the previous release of TatSu should hold for more than long enough.

**Comment by apalala** [comment]
I'm closing this old PR, @Victorious3. Just reopen if there will be work on it?

**Pull request closed without merging**
